apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-openj9-deployment
spec:
  selector:
    matchLabels:
      app: demo-spring-openj9
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-spring-openj9
    spec:
      containers:
        - name: demo-spring-openj9
          image: phayao/demo-spring-openj9:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: demo-spring-openj9
spec:
  selector:
    app: demo-spring-openj9
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080