apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-openj9-warm-deployment
spec:
  selector:
    matchLabels:
      app: demo-spring-openj9-warm
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-spring-openj9-warm
    spec:
      containers:
        - name: demo-spring-openj9-warm
          image: phayao/demo-spring-openj9-warm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 25
---
apiVersion: v1
kind: Service
metadata:
  name: demo-spring-openj9-warm
spec:
  selector:
    app: demo-spring-openj9-warm
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080